blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    about: üó® Start a friendly conversation with the other members of the community about the samples in this repository.
    url: https://github.com/pnp/powerapps-samples/discussions
  - name: Microsoft Tech Community
    url: https://techcommunity.microsoft.com/t5/power-platform/bd-p/PowerPlatform
    about: ‚ÅâÔ∏è Alternatively, submit your technical questions in the Power Platform Tech Community